swagger: "2.0"
info:
  title: Example APO
  version: 1.0.0
paths:
  /users:
    post:
      summary: Создание нового пользователя
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: Пользователь успешно создан
    get:
      summary: Получение информации о всех пользователях
      responses:
        200:
          description: Список всех пользователей
  /users/{userId}:
    get:
      summary: Получение информации о пользователе по идентификатору
      parameters:
        - in: path
          name: userId
          required: true
          type: integer
      responses:
        200:
          description: Информация о пользователе
    put:
      summary: Обновление информации о пользователе
      parameters:
        - in: path
          name: userId
          required: true
          type: integer
        - in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: Успешное обновление информации о пользователе
    delete:
      summary: Удаление пользователя по идентификатору
      parameters:
        - in: path
          name: userId
          required: true
          type: integer
      responses:
        204:
          description: Пользователь успешно удален
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
    required:
      - name
      - email
