# Site settings
course_name: Практикум по разработке ML сервисво
course_semester: "осень 2023"
course_description: В рамках этого курса вы познакомитесь с основными этапами жизненного цикла ML-модели, начиная от сбора и подготовки данных, до развертывания и мониторинга ML-сервиса. Мы рассмотрим различные инструменты и технологии, которые помогут вам разрабатывать и внедрять ML-сервисы в реальных сценариях.

baseurl: "/Practice-ML-DEV" # the subpath of your site, e.g. /blog/
url: "http://yanchick.github.io/" # the base hostname & protocol for your site

schoolname: "ITMO"
schoolurl: "https://itmo.ru"

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css','_sass']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: false
    lectures:
        output: false
    assignments:
        output: false
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
